"""Random testing"""

import tkinter as tk
from generallibrary import initBases, getBaseClasses, CodeGen
import pickle

from generalgui import Label




import json

class Config:
    """ Easily read and change attributes with generated code for auto-completion. """
    def _generate_code(self, cls_name, **kwargs):
        """ Generate Python code for new class that inherits Config. """
        code = CodeGen()
        code.add(0, f"class {cls_name}:")
        code.add(1, f'""" CLASS CODE GENERATED BY `CodeGen` THROUGH `Config._generated_code()`. """')
        code.add(1, f"def __init__(self):")
        for name, default in kwargs.items():
            code.add(2, f"self._{name} = {json.dumps(default)}")

        for name, default in kwargs.items():
            code.add(1, f"@property", 1)
            code.add(1, f"def {name}(self):")
            code.add(2, f"return self._{name}")

        args = ", ".join([f"{name}=None" for name in kwargs])

        code.add(1, f"def config(self, {args}):", 1)
        code.add(2, f"for key, value in locals().items():")
        code.add(3, f"if key != \"self\" and value is not None:")
        code.add(4, f"setattr(self, \"_\" + key, value)")

        code.print()



# Need config to create a class that's easily changeable with hooks

# Config()._generate_code("Test", a=1, foo="bar")

# HERE ** Learning git subtree add in SSH







